# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/klejs/src/gcg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/klejs/src/gcg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/klejs/src/gcg/CMakeFiles /home/klejs/src/gcg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/klejs/src/gcg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named gcg

# Build rule for target.
gcg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gcg
.PHONY : gcg

# fast build rule for target.
gcg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/build
.PHONY : gcg/fast

home/klejs/src/ImGui/backends/imgui_impl_sdl3.o: home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.o
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.o

# target to build an object file
home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.o
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.o

home/klejs/src/ImGui/backends/imgui_impl_sdl3.i: home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.i
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.i

# target to preprocess a source file
home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.i
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.i

home/klejs/src/ImGui/backends/imgui_impl_sdl3.s: home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.s
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.s

# target to generate assembly for a file
home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.s
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.s

home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.o: home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.o
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.o

# target to build an object file
home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.o
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.o

home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.i: home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.i
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.i

# target to preprocess a source file
home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.i
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.i

home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.s: home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.s
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.s

# target to generate assembly for a file
home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.s
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.cpp.s

home/klejs/src/ImGui/imgui.o: home/klejs/src/ImGui/imgui.cpp.o
.PHONY : home/klejs/src/ImGui/imgui.o

# target to build an object file
home/klejs/src/ImGui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui.cpp.o
.PHONY : home/klejs/src/ImGui/imgui.cpp.o

home/klejs/src/ImGui/imgui.i: home/klejs/src/ImGui/imgui.cpp.i
.PHONY : home/klejs/src/ImGui/imgui.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui.cpp.i
.PHONY : home/klejs/src/ImGui/imgui.cpp.i

home/klejs/src/ImGui/imgui.s: home/klejs/src/ImGui/imgui.cpp.s
.PHONY : home/klejs/src/ImGui/imgui.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui.cpp.s
.PHONY : home/klejs/src/ImGui/imgui.cpp.s

home/klejs/src/ImGui/imgui_demo.o: home/klejs/src/ImGui/imgui_demo.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_demo.o

# target to build an object file
home/klejs/src/ImGui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_demo.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_demo.cpp.o

home/klejs/src/ImGui/imgui_demo.i: home/klejs/src/ImGui/imgui_demo.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_demo.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_demo.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_demo.cpp.i

home/klejs/src/ImGui/imgui_demo.s: home/klejs/src/ImGui/imgui_demo.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_demo.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_demo.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_demo.cpp.s

home/klejs/src/ImGui/imgui_draw.o: home/klejs/src/ImGui/imgui_draw.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_draw.o

# target to build an object file
home/klejs/src/ImGui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_draw.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_draw.cpp.o

home/klejs/src/ImGui/imgui_draw.i: home/klejs/src/ImGui/imgui_draw.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_draw.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_draw.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_draw.cpp.i

home/klejs/src/ImGui/imgui_draw.s: home/klejs/src/ImGui/imgui_draw.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_draw.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_draw.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_draw.cpp.s

home/klejs/src/ImGui/imgui_tables.o: home/klejs/src/ImGui/imgui_tables.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_tables.o

# target to build an object file
home/klejs/src/ImGui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_tables.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_tables.cpp.o

home/klejs/src/ImGui/imgui_tables.i: home/klejs/src/ImGui/imgui_tables.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_tables.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_tables.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_tables.cpp.i

home/klejs/src/ImGui/imgui_tables.s: home/klejs/src/ImGui/imgui_tables.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_tables.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_tables.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_tables.cpp.s

home/klejs/src/ImGui/imgui_widgets.o: home/klejs/src/ImGui/imgui_widgets.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_widgets.o

# target to build an object file
home/klejs/src/ImGui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_widgets.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_widgets.cpp.o

home/klejs/src/ImGui/imgui_widgets.i: home/klejs/src/ImGui/imgui_widgets.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_widgets.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_widgets.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_widgets.cpp.i

home/klejs/src/ImGui/imgui_widgets.s: home/klejs/src/ImGui/imgui_widgets.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_widgets.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_widgets.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_widgets.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gcg"
	@echo "... imgui"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdl3.o"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdl3.i"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdl3.s"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.o"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.i"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdlrenderer3.s"
	@echo "... home/klejs/src/ImGui/imgui.o"
	@echo "... home/klejs/src/ImGui/imgui.i"
	@echo "... home/klejs/src/ImGui/imgui.s"
	@echo "... home/klejs/src/ImGui/imgui_demo.o"
	@echo "... home/klejs/src/ImGui/imgui_demo.i"
	@echo "... home/klejs/src/ImGui/imgui_demo.s"
	@echo "... home/klejs/src/ImGui/imgui_draw.o"
	@echo "... home/klejs/src/ImGui/imgui_draw.i"
	@echo "... home/klejs/src/ImGui/imgui_draw.s"
	@echo "... home/klejs/src/ImGui/imgui_tables.o"
	@echo "... home/klejs/src/ImGui/imgui_tables.i"
	@echo "... home/klejs/src/ImGui/imgui_tables.s"
	@echo "... home/klejs/src/ImGui/imgui_widgets.o"
	@echo "... home/klejs/src/ImGui/imgui_widgets.i"
	@echo "... home/klejs/src/ImGui/imgui_widgets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

