# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/klejs/src/gcg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/klejs/src/gcg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/klejs/src/gcg/CMakeFiles /home/klejs/src/gcg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/klejs/src/gcg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named gcg

# Build rule for target.
gcg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gcg
.PHONY : gcg

# fast build rule for target.
gcg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/build
.PHONY : gcg/fast

godot_manager.o: godot_manager.cpp.o
.PHONY : godot_manager.o

# target to build an object file
godot_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/godot_manager.cpp.o
.PHONY : godot_manager.cpp.o

godot_manager.i: godot_manager.cpp.i
.PHONY : godot_manager.i

# target to preprocess a source file
godot_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/godot_manager.cpp.i
.PHONY : godot_manager.cpp.i

godot_manager.s: godot_manager.cpp.s
.PHONY : godot_manager.s

# target to generate assembly for a file
godot_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/godot_manager.cpp.s
.PHONY : godot_manager.cpp.s

godot_renderer.o: godot_renderer.cpp.o
.PHONY : godot_renderer.o

# target to build an object file
godot_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/godot_renderer.cpp.o
.PHONY : godot_renderer.cpp.o

godot_renderer.i: godot_renderer.cpp.i
.PHONY : godot_renderer.i

# target to preprocess a source file
godot_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/godot_renderer.cpp.i
.PHONY : godot_renderer.cpp.i

godot_renderer.s: godot_renderer.cpp.s
.PHONY : godot_renderer.s

# target to generate assembly for a file
godot_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/godot_renderer.cpp.s
.PHONY : godot_renderer.cpp.s

home/klejs/src/ImGui/backends/imgui_impl_sdl3.o: home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.o
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.o

# target to build an object file
home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.o
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.o

home/klejs/src/ImGui/backends/imgui_impl_sdl3.i: home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.i
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.i

# target to preprocess a source file
home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.i
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.i

home/klejs/src/ImGui/backends/imgui_impl_sdl3.s: home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.s
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.s

# target to generate assembly for a file
home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.s
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdl3.cpp.s

home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.o: home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.o
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.o

# target to build an object file
home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.o
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.o

home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.i: home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.i
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.i

# target to preprocess a source file
home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.i
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.i

home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.s: home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.s
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.s

# target to generate assembly for a file
home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.s
.PHONY : home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.cpp.s

home/klejs/src/ImGui/imgui.o: home/klejs/src/ImGui/imgui.cpp.o
.PHONY : home/klejs/src/ImGui/imgui.o

# target to build an object file
home/klejs/src/ImGui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui.cpp.o
.PHONY : home/klejs/src/ImGui/imgui.cpp.o

home/klejs/src/ImGui/imgui.i: home/klejs/src/ImGui/imgui.cpp.i
.PHONY : home/klejs/src/ImGui/imgui.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui.cpp.i
.PHONY : home/klejs/src/ImGui/imgui.cpp.i

home/klejs/src/ImGui/imgui.s: home/klejs/src/ImGui/imgui.cpp.s
.PHONY : home/klejs/src/ImGui/imgui.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui.cpp.s
.PHONY : home/klejs/src/ImGui/imgui.cpp.s

home/klejs/src/ImGui/imgui_demo.o: home/klejs/src/ImGui/imgui_demo.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_demo.o

# target to build an object file
home/klejs/src/ImGui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_demo.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_demo.cpp.o

home/klejs/src/ImGui/imgui_demo.i: home/klejs/src/ImGui/imgui_demo.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_demo.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_demo.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_demo.cpp.i

home/klejs/src/ImGui/imgui_demo.s: home/klejs/src/ImGui/imgui_demo.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_demo.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_demo.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_demo.cpp.s

home/klejs/src/ImGui/imgui_draw.o: home/klejs/src/ImGui/imgui_draw.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_draw.o

# target to build an object file
home/klejs/src/ImGui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_draw.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_draw.cpp.o

home/klejs/src/ImGui/imgui_draw.i: home/klejs/src/ImGui/imgui_draw.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_draw.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_draw.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_draw.cpp.i

home/klejs/src/ImGui/imgui_draw.s: home/klejs/src/ImGui/imgui_draw.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_draw.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_draw.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_draw.cpp.s

home/klejs/src/ImGui/imgui_tables.o: home/klejs/src/ImGui/imgui_tables.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_tables.o

# target to build an object file
home/klejs/src/ImGui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_tables.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_tables.cpp.o

home/klejs/src/ImGui/imgui_tables.i: home/klejs/src/ImGui/imgui_tables.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_tables.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_tables.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_tables.cpp.i

home/klejs/src/ImGui/imgui_tables.s: home/klejs/src/ImGui/imgui_tables.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_tables.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_tables.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_tables.cpp.s

home/klejs/src/ImGui/imgui_widgets.o: home/klejs/src/ImGui/imgui_widgets.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_widgets.o

# target to build an object file
home/klejs/src/ImGui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_widgets.cpp.o
.PHONY : home/klejs/src/ImGui/imgui_widgets.cpp.o

home/klejs/src/ImGui/imgui_widgets.i: home/klejs/src/ImGui/imgui_widgets.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_widgets.i

# target to preprocess a source file
home/klejs/src/ImGui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_widgets.cpp.i
.PHONY : home/klejs/src/ImGui/imgui_widgets.cpp.i

home/klejs/src/ImGui/imgui_widgets.s: home/klejs/src/ImGui/imgui_widgets.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_widgets.s

# target to generate assembly for a file
home/klejs/src/ImGui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/home/klejs/src/ImGui/imgui_widgets.cpp.s
.PHONY : home/klejs/src/ImGui/imgui_widgets.cpp.s

input_manager.o: input_manager.cpp.o
.PHONY : input_manager.o

# target to build an object file
input_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/input_manager.cpp.o
.PHONY : input_manager.cpp.o

input_manager.i: input_manager.cpp.i
.PHONY : input_manager.i

# target to preprocess a source file
input_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/input_manager.cpp.i
.PHONY : input_manager.cpp.i

input_manager.s: input_manager.cpp.s
.PHONY : input_manager.s

# target to generate assembly for a file
input_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/input_manager.cpp.s
.PHONY : input_manager.cpp.s

luascripting.o: luascripting.cpp.o
.PHONY : luascripting.o

# target to build an object file
luascripting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/luascripting.cpp.o
.PHONY : luascripting.cpp.o

luascripting.i: luascripting.cpp.i
.PHONY : luascripting.i

# target to preprocess a source file
luascripting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/luascripting.cpp.i
.PHONY : luascripting.cpp.i

luascripting.s: luascripting.cpp.s
.PHONY : luascripting.s

# target to generate assembly for a file
luascripting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/luascripting.cpp.s
.PHONY : luascripting.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/main.cpp.s
.PHONY : main.cpp.s

renderer.o: renderer.cpp.o
.PHONY : renderer.o

# target to build an object file
renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/renderer.cpp.o
.PHONY : renderer.cpp.o

renderer.i: renderer.cpp.i
.PHONY : renderer.i

# target to preprocess a source file
renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/renderer.cpp.i
.PHONY : renderer.cpp.i

renderer.s: renderer.cpp.s
.PHONY : renderer.s

# target to generate assembly for a file
renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/renderer.cpp.s
.PHONY : renderer.cpp.s

resource_format_loader_gltf.o: resource_format_loader_gltf.cpp.o
.PHONY : resource_format_loader_gltf.o

# target to build an object file
resource_format_loader_gltf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/resource_format_loader_gltf.cpp.o
.PHONY : resource_format_loader_gltf.cpp.o

resource_format_loader_gltf.i: resource_format_loader_gltf.cpp.i
.PHONY : resource_format_loader_gltf.i

# target to preprocess a source file
resource_format_loader_gltf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/resource_format_loader_gltf.cpp.i
.PHONY : resource_format_loader_gltf.cpp.i

resource_format_loader_gltf.s: resource_format_loader_gltf.cpp.s
.PHONY : resource_format_loader_gltf.s

# target to generate assembly for a file
resource_format_loader_gltf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/resource_format_loader_gltf.cpp.s
.PHONY : resource_format_loader_gltf.cpp.s

resource_format_loader_png.o: resource_format_loader_png.cpp.o
.PHONY : resource_format_loader_png.o

# target to build an object file
resource_format_loader_png.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/resource_format_loader_png.cpp.o
.PHONY : resource_format_loader_png.cpp.o

resource_format_loader_png.i: resource_format_loader_png.cpp.i
.PHONY : resource_format_loader_png.i

# target to preprocess a source file
resource_format_loader_png.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/resource_format_loader_png.cpp.i
.PHONY : resource_format_loader_png.cpp.i

resource_format_loader_png.s: resource_format_loader_png.cpp.s
.PHONY : resource_format_loader_png.s

# target to generate assembly for a file
resource_format_loader_png.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/resource_format_loader_png.cpp.s
.PHONY : resource_format_loader_png.cpp.s

resource_format_loader_wav.o: resource_format_loader_wav.cpp.o
.PHONY : resource_format_loader_wav.o

# target to build an object file
resource_format_loader_wav.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/resource_format_loader_wav.cpp.o
.PHONY : resource_format_loader_wav.cpp.o

resource_format_loader_wav.i: resource_format_loader_wav.cpp.i
.PHONY : resource_format_loader_wav.i

# target to preprocess a source file
resource_format_loader_wav.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/resource_format_loader_wav.cpp.i
.PHONY : resource_format_loader_wav.cpp.i

resource_format_loader_wav.s: resource_format_loader_wav.cpp.s
.PHONY : resource_format_loader_wav.s

# target to generate assembly for a file
resource_format_loader_wav.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/resource_format_loader_wav.cpp.s
.PHONY : resource_format_loader_wav.cpp.s

shplasma.o: shplasma.cpp.o
.PHONY : shplasma.o

# target to build an object file
shplasma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/shplasma.cpp.o
.PHONY : shplasma.cpp.o

shplasma.i: shplasma.cpp.i
.PHONY : shplasma.i

# target to preprocess a source file
shplasma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/shplasma.cpp.i
.PHONY : shplasma.cpp.i

shplasma.s: shplasma.cpp.s
.PHONY : shplasma.s

# target to generate assembly for a file
shplasma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gcg.dir/build.make CMakeFiles/gcg.dir/shplasma.cpp.s
.PHONY : shplasma.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gcg"
	@echo "... imgui"
	@echo "... godot_manager.o"
	@echo "... godot_manager.i"
	@echo "... godot_manager.s"
	@echo "... godot_renderer.o"
	@echo "... godot_renderer.i"
	@echo "... godot_renderer.s"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdl3.o"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdl3.i"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdl3.s"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.o"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.i"
	@echo "... home/klejs/src/ImGui/backends/imgui_impl_sdlgpu3.s"
	@echo "... home/klejs/src/ImGui/imgui.o"
	@echo "... home/klejs/src/ImGui/imgui.i"
	@echo "... home/klejs/src/ImGui/imgui.s"
	@echo "... home/klejs/src/ImGui/imgui_demo.o"
	@echo "... home/klejs/src/ImGui/imgui_demo.i"
	@echo "... home/klejs/src/ImGui/imgui_demo.s"
	@echo "... home/klejs/src/ImGui/imgui_draw.o"
	@echo "... home/klejs/src/ImGui/imgui_draw.i"
	@echo "... home/klejs/src/ImGui/imgui_draw.s"
	@echo "... home/klejs/src/ImGui/imgui_tables.o"
	@echo "... home/klejs/src/ImGui/imgui_tables.i"
	@echo "... home/klejs/src/ImGui/imgui_tables.s"
	@echo "... home/klejs/src/ImGui/imgui_widgets.o"
	@echo "... home/klejs/src/ImGui/imgui_widgets.i"
	@echo "... home/klejs/src/ImGui/imgui_widgets.s"
	@echo "... input_manager.o"
	@echo "... input_manager.i"
	@echo "... input_manager.s"
	@echo "... luascripting.o"
	@echo "... luascripting.i"
	@echo "... luascripting.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... renderer.o"
	@echo "... renderer.i"
	@echo "... renderer.s"
	@echo "... resource_format_loader_gltf.o"
	@echo "... resource_format_loader_gltf.i"
	@echo "... resource_format_loader_gltf.s"
	@echo "... resource_format_loader_png.o"
	@echo "... resource_format_loader_png.i"
	@echo "... resource_format_loader_png.s"
	@echo "... resource_format_loader_wav.o"
	@echo "... resource_format_loader_wav.i"
	@echo "... resource_format_loader_wav.s"
	@echo "... shplasma.o"
	@echo "... shplasma.i"
	@echo "... shplasma.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

